"""
AgriDecision AI - Common Security Utilities
============================================
Provides JWT token creation, validation, and password/OTP hashing logic.

Security hardening applied:
  - iss (issuer) and aud (audience) claims now mandatory in all tokens
  - decode_token() validates iss and aud on every call
  - OTP hashing utilities using HMAC-SHA256 (OTPs not stored plaintext)
  - Constant-time comparison for OTP verification (timing-attack resistant)
"""
import hashlib
import hmac
import secrets
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from jose import JWTError, jwt
from passlib.context import CryptContext

from backend.common.exceptions import UnauthorizedException

# ── Constants ──────────────────────────────────────────────────────────────────
JWT_ISSUER = "agridecision.ai"
JWT_AUDIENCE = "agridecision-api"

# Global context for password/secret hashing (bcrypt, work factor 12)
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto", bcrypt__rounds=12)


# ── Password Utilities ─────────────────────────────────────────────────────────

def verify_password(plain_password: str, hashed_password: str) -> bool:
    """Verify a plain password against a bcrypt hash."""
    return pwd_context.verify(plain_password, hashed_password)


def get_password_hash(password: str) -> str:
    """Hash a password using bcrypt (work factor 12)."""
    return pwd_context.hash(password)


# ── OTP Utilities (HMAC-SHA256) ────────────────────────────────────────────────

def hash_otp(otp_code: str, hmac_secret: str) -> str:
    """
    Return an HMAC-SHA256 hex digest of the OTP.
    Store only the digest in Redis — never the plaintext OTP.

    Args:
        otp_code:    The 6-digit OTP generated by secrets.randbelow()
        hmac_secret: Service-level secret for HMAC keying (read from Vault/env)

    Returns:
        64-character hex string (SHA-256 digest)
    """
    return hmac.new(
        hmac_secret.encode("utf-8"),
        otp_code.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()


def verify_otp_hash(candidate_otp: str, stored_hash: str, hmac_secret: str) -> bool:
    """
    Constant-time comparison of candidate OTP against stored HMAC digest.
    Prevents timing attacks on OTP verification.

    Returns True only if candidate OTP matches the stored hash.
    """
    candidate_hash = hash_otp(candidate_otp, hmac_secret)
    return hmac.compare_digest(candidate_hash, stored_hash)


# ── JWT Token Utilities ────────────────────────────────────────────────────────

def create_access_token(
    data: dict,
    secret_key: str,
    algorithm: str = "HS256",
    expires_delta: Optional[timedelta] = None,
    audience: str = JWT_AUDIENCE,
    issuer: str = JWT_ISSUER,
) -> str:
    """
    Create a signed JWT access token.

    Security properties:
      - Includes iss (issuer) claim → validates token origin
      - Includes aud (audience) claim → prevents token reuse across APIs
      - Expires in 15 minutes by default (short-lived)
      - Token type claim "access" prevents refresh tokens being used as access tokens
    """
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + (expires_delta or timedelta(minutes=15))
    to_encode.update({
        "exp": expire,
        "iat": datetime.now(timezone.utc),
        "iss": issuer,
        "aud": audience,
        "type": "access",
    })
    return jwt.encode(to_encode, secret_key, algorithm=algorithm)


def create_refresh_token(
    data: dict,
    secret_key: str,
    algorithm: str = "HS256",
    expires_delta: Optional[timedelta] = None,
    audience: str = JWT_AUDIENCE,
    issuer: str = JWT_ISSUER,
) -> str:
    """
    Create a signed JWT refresh token.

    Security properties:
      - Token type claim "refresh" distinguishes it from access tokens
      - Refresh tokens are hashed (SHA-256) before storage — never stored raw
      - Expires in 30 days by default
    """
    to_encode = data.copy()
    expire = datetime.now(timezone.utc) + (expires_delta or timedelta(days=30))
    to_encode.update({
        "exp": expire,
        "iat": datetime.now(timezone.utc),
        "iss": issuer,
        "aud": audience,
        "type": "refresh",
    })
    return jwt.encode(to_encode, secret_key, algorithm=algorithm)


def decode_token(
    token: str,
    secret_key: str,
    algorithm: str = "HS256",
    audience: str = JWT_AUDIENCE,
    issuer: str = JWT_ISSUER,
) -> Dict[str, Any]:
    """
    Decode and validate a JWT token.

    Validations performed:
      - Signature verification
      - Expiry (exp claim) — jose validates automatically
      - Issuer (iss claim) — raises if not agridecision.ai
      - Audience (aud claim) — raises if not agridecision-api
      - Subject (sub claim) present
    """
    try:
        payload = jwt.decode(
            token,
            secret_key,
            algorithms=[algorithm],
            audience=audience,
            issuer=issuer,
            options={"require": ["exp", "iat", "iss", "aud", "sub"]},
        )
        return payload
    except JWTError as e:
        raise UnauthorizedException(detail=f"Could not validate credentials: {str(e)}")


def hash_token(token: str) -> str:
    """
    Return a SHA-256 hex digest of a JWT token string.
    Used for:
      - Storing refresh token hashes (never the raw token)
      - Token blacklist keys in Redis
    """
    return hashlib.sha256(token.encode("utf-8")).hexdigest()
