"""
Farm Service - Dependencies
Instantiates database and Kafka managers and wires them to common dependencies.
"""
from backend.common.database import DatabaseManager
from backend.common.dependencies import get_current_user_dependency, get_db_dependency
from backend.common.kafka import KafkaManager
from backend.services.farm_service.src.config import settings
from fastapi import Request
from redis.asyncio import Redis

# Global singletons initialized during application startup
db_manager = DatabaseManager(settings.DATABASE_URL)
kafka_manager = KafkaManager(settings.KAFKA_BOOTSTRAP_SERVERS)
redis_client = Redis.from_url(settings.REDIS_URL, decode_responses=True)

# Exported dependencies for FastAPI routers
get_db = get_db_dependency(db_manager)

# The user payload dependency. The token is generated by the user-service and validated here
# using the shared JWT secret key.
get_current_user = get_current_user_dependency(settings.JWT_SECRET_KEY, settings.JWT_ALGORITHM)

async def get_redis(request: Request) -> Redis:
    """Dependency to provide Redis client."""
    return redis_client
